### ISSUE TITLE
error solve kor

### ISSUE THREAD

**Issue by abubakar38** [straselhossen/mcart#2]
hi

**Comment by straselhossen** [comment]
tuy kida

**Comment by abubakar38** [comment]
what the fucks

**Comment by foyzur17** [comment]
error fixed

**Comment by straselhossen** [comment]
ki dhon lekha lekhi koris

**Comment by abubakar38** [comment]
ami jani k pokki marvo

**Comment by yasinalibd02** [comment]
this is simple problem ,i will solve this problem just 5 minutes

**Comment by joyahmed10** [comment]
sznjkfgnakjl;nsefjnjkwANJKEFNJK;awnefjkn
sdafmkajklesfjljqLWFK
SD;LAKLGJWKLaeiofjk
sda;kfl;AWJFROPIJ
ael;fgjwaopjfop
e;'wkfkopwq
\
;'
dldss;aklfkopawkpe

**Comment by joyahmed10** [comment]
গডহসহহস

**Comment by straselhossen** [comment]
tuy to puray banchod

**Comment by yasinalibd02** [comment]
bukachuda what's your problem

**Comment by straselhossen** [comment]
tor oxizen lagto naki

**Comment by joyahmed10** [comment]
![IMG20220204185238.jpg](https://user-images.githubusercontent.com/97307036/152585183-bf7721e0-3194-44a7-a263-10ea46947fe7.jpg)

**Comment by abubakar38** [comment]
sob mal khor

**Comment by yasinalibd02** [comment]
W
T
F

**Comment by joyahmed10** [comment]
![FB_IMG_1644000344278.jpg](https://user-images.githubusercontent.com/97307036/152585470-553d22b4-bed2-4362-9580-7047f75246cc.jpg)

**Comment by abubakar38** [comment]
_**love u gusy**_

**Comment by yasinalibd02** [comment]
wow what the

**Comment by foyzur17** [comment]
My idol

**Comment by straselhossen** [comment]
![download](https://user-images.githubusercontent.com/92251907/152585722-76d974e5-770c-4b35-a801-979d695846fe.png)

**Comment by straselhossen** [comment]
![Uploading Screenshot (1).png…]()
